# Generated by Django 5.0.14 on 2026-06-19 14:17

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('barber', 'Barber / Salon'), ('clinic', 'Clinic'), ('general', 'General')], default='general', max_length=32)),
                ('experience', models.CharField(choices=[('barber', 'Barber / Salon'), ('clinic', 'Clinic'), ('general', 'General')], default='general', max_length=32)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('suspended', 'Suspended')], default='trial', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('has_booking', models.BooleanField(default=True)),
                ('has_accounting', models.BooleanField(default=False)),
                ('has_records', models.BooleanField(default=False)),
                ('has_bots', models.BooleanField(default=False)),
                ('has_sms', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenancy_business',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.business')),
            ],
            options={
                'db_table': 'tenancy_domain',
            },
        ),
    ]
