"""MCP Server models for internal tokens and audit logging."""

import secrets
from django.db import models
from django.utils import timezone


class MCPInternalToken(models.Model):
    """Short-lived tokens for Qwen container to call back to MCP.

    Tokens are:
    - Generated by Django when user sends chat message
    - Passed to Qwen container
    - Used by Qwen to call back to /api/mcp/internal
    - Validated on each MCP request
    - Single-use or short-lived (5 minutes)
    """

    token = models.CharField(max_length=64, unique=True, db_index=True)
    tenant = models.ForeignKey("tenancy.Tenant", on_delete=models.CASCADE)
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    scopes = models.JSONField(default=list)  # List of permission strings
    expires_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    used_at = models.DateTimeField(null=True, blank=True)
    is_revoked = models.BooleanField(default=False)

    class Meta:
        db_table = "mcp_internal_token"
        indexes = [
            models.Index(fields=["token"]),
            models.Index(fields=["expires_at"]),
            models.Index(fields=["tenant", "user"]),
        ]

    def __str__(self):
        return f"Token for {self.user.email} in {self.tenant.schema_name}"

    def is_valid(self):
        """Check if token is valid and not expired."""
        if self.is_revoked:
            return False
        return timezone.now() < self.expires_at

    @classmethod
    def generate(cls, tenant, user, scopes, expires_seconds=300):
        """Generate a new internal token."""
        token = secrets.token_urlsafe(48)
        from datetime import timedelta
        expires_at = timezone.now() + timedelta(seconds=expires_seconds)
        return cls.objects.create(
            token=token,
            tenant=tenant,
            user=user,
            scopes=scopes,
            expires_at=expires_at,
        )


class MCPRequestAudit(models.Model):
    """Audit all MCP requests for security and debugging."""

    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    tenant = models.ForeignKey("tenancy.Tenant", on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey("accounts.User", on_delete=models.SET_NULL, null=True)
    token = models.ForeignKey(MCPInternalToken, on_delete=models.SET_NULL, null=True)

    # Request details
    source = models.CharField(max_length=20)  # 'internal' or 'external'
    tool_name = models.CharField(max_length=100, null=True, blank=True)
    resource_uri = models.CharField(max_length=255, null=True, blank=True)
    parameters = models.JSONField(null=True, blank=True)

    # Response
    status = models.CharField(max_length=20)  # 'success', 'forbidden', 'error'
    duration_ms = models.IntegerField(null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)

    # Metadata
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "mcp_request_audit"
        indexes = [
            models.Index(fields=["timestamp"]),
            models.Index(fields=["tenant", "status"]),
            models.Index(fields=["tool_name"]),
        ]

    def __str__(self):
        return f"{self.tool_name or self.resource_uri} - {self.status}"


def cleanup_expired_tokens():
    """Remove expired tokens (called by celery beat)."""
    from django.utils import timezone
    return MCPInternalToken.objects.filter(expires_at__lt=timezone.now()).delete()


def cleanup_old_audit_logs(days=30):
    """Remove audit logs older than specified days."""
    from django.utils import timezone
    from datetime import timedelta
    cutoff = timezone.now() - timedelta(days=days)
    return MCPRequestAudit.objects.filter(timestamp__lt=cutoff).delete()
