# Generated by Django 5.0.14 on 2026-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_migrate_transactions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="uniq_income_per_appointment",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_appointment_id__isnull", False)),
                fields=("source_appointment_id",),
                name="uniq_transaction_per_appointment",
            ),
        ),
    ]
