# Generated by Django 5.0.14 on 2026-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#111827', max_length=9)),
                ('accent_color', models.CharField(default='#2563eb', max_length=9)),
                ('vocabulary', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('booking_lead_minutes', models.PositiveIntegerField(default=60)),
                ('max_advance_days', models.PositiveIntegerField(default=60)),
                ('cancellation_window_hours', models.PositiveIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_profile',
            },
        ),
    ]
