# Generated by Django 5.0.14 on 2026-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="require_phone_otp",
            field=models.BooleanField(default=True),
        ),
    ]
