# Generated by Django 5.0.14 on 2026-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=32)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("signup", "Owner sign-up"), ("booking", "Customer booking")],
                        max_length=16,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "otp_code",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["identifier", "purpose", "created_at"],
                        name="otp_code_identif_fba827_idx",
                    )
                ],
            },
        ),
    ]
