# Generated by Django 5.0.14 on 2026-06-19 14:41

import apps.bots.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Booking assistant', max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('greeting', models.CharField(default='Hi! I can help you book an appointment.', max_length=500)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('exposed_service_ids', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('secret', models.CharField(db_index=True, default=apps.bots.models._gen_token, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bots_bot',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='web', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bots.bot')),
            ],
            options={
                'db_table': 'bots_conversation',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=8)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bots.conversation')),
            ],
            options={
                'db_table': 'bots_message',
                'ordering': ('created_at',),
            },
        ),
    ]
