# Generated by Django 5.0.14 on 2026-06-20 09:20

import apps.bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_bot_telegram_bot_token_bot_telegram_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bale_bot_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="bot",
            name="bale_webhook_secret",
            field=models.CharField(
                db_index=True, default=apps.bots.models._gen_token, max_length=64
            ),
        ),
    ]
