# Generated by Django 5.0.14 on 2026-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('permission_change', 'Permission change'), ('record_access', 'Record access'), ('impersonation', 'Impersonation'), ('booking_override', 'Booking override'), ('data_export', 'Data export')], max_length=40)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
