# Generated by Django 5.0.14 on 2026-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('kind', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('reschedule', 'Reschedule'), ('cancellation', 'Cancellation')], max_length=20)),
                ('appointment_id', models.BigIntegerField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead', 'Dead-lettered')], default='queued', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
